version: "3"
services:

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - application

  application:
    build: .
    ports:
      - 8080:8080
    restart: always
