spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
