---- ROOT
--INSERT INTO CATEGORY VALUES (1, now(), now(), true, '패션의류/잡화', NULL);
--INSERT INTO CATEGORY VALUES (2, now(), now(), true, '뷰티', NULL);
--INSERT INTO CATEGORY VALUES (3, now(), now(), true, '출산/유아동', NULL);
--INSERT INTO CATEGORY VALUES (4, now(), now(), true, '식품', NULL);
--INSERT INTO CATEGORY VALUES (5, now(), now(), true, '주방용품', NULL);
--INSERT INTO CATEGORY VALUES (6, now(), now(), true, '생활용품', NULL);
--INSERT INTO CATEGORY VALUES (7, now(), now(), true, '헤어/바디/세안', 6);
--INSERT INTO CATEGORY VALUES (8, now(), now(), true, '샴푸/린스', 7);
--INSERT INTO CATEGORY VALUES (9, now(), now(), true, '구강/면도', 6);
